# Generated by Django 6.0.5 on 2026-06-17 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('division', models.CharField(max_length=20)),
                ('current_project', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=30)),
                ('about', models.TextField(blank=True, default='No bio or description provided yet.')),
                ('rfid_num', models.CharField(max_length=8)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Present', max_length=20)),
                ('Teammates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.teammates')),
            ],
        ),
    ]
